[package]
name = "rubust"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
bitset = "0.1.2"
regex = "1.5.5"
num_enum = "0.5.7"
thiserror = "1.0.30"
